
/* This file was generated by idltool 53.1. Do not edit */

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif
#ifndef LIBRARIES_AHI_SUB_H
#include <libraries/ahi_sub.h>
#endif

extern uint32                  VARARGS68K _usbaudio_Obtain(struct USBAudioIFace *);
extern uint32                  VARARGS68K _usbaudio_Release(struct USBAudioIFace *);
extern struct USBAudioIFace *  VARARGS68K _usbaudio_Clone(struct USBAudioIFace *);
extern uint32                  VARARGS68K _usbaudio_AHIsub_AllocAudio(struct USBAudioIFace *, struct TagItem *tagList, struct AHIAudioCtrlDrv *AudioCtrl);
extern void                    VARARGS68K _usbaudio_AHIsub_FreeAudio(struct USBAudioIFace *, struct AHIAudioCtrlDrv *AudioCtrl);
extern void                    VARARGS68K _usbaudio_AHIsub_Disable(struct USBAudioIFace *, struct AHIAudioCtrlDrv *AudioCtrl);
extern void                    VARARGS68K _usbaudio_AHIsub_Enable(struct USBAudioIFace *, struct AHIAudioCtrlDrv *AudioCtrl);
extern uint32                  VARARGS68K _usbaudio_AHIsub_Start(struct USBAudioIFace *, uint32 Flags, struct AHIAudioCtrlDrv *AudioCtrl);
extern uint32                  VARARGS68K _usbaudio_AHIsub_Update(struct USBAudioIFace *, uint32 Flags, struct AHIAudioCtrlDrv *AudioCtrl);
extern uint32                  VARARGS68K _usbaudio_AHIsub_Stop(struct USBAudioIFace *, uint32 Flags, struct AHIAudioCtrlDrv *AudioCtrl);
extern uint32                  VARARGS68K _usbaudio_AHIsub_SetVol(struct USBAudioIFace *, uint16 Channel, Fixed Volume, sposition Pan, struct AHIAudioCtrlDrv *AudioCtrl, uint32 Flags);
extern uint32                  VARARGS68K _usbaudio_AHIsub_SetFreq(struct USBAudioIFace *, uint16 Channel, uint32 Freq, struct AHIAudioCtrlDrv *AudioCtrl, uint32 Flags);
extern uint32                  VARARGS68K _usbaudio_AHIsub_SetSound(struct USBAudioIFace *, uint16 Channel, uint16 Sound, uint32 Offset, int32 Lenght, struct AHIAudioCtrlDrv *AudioCtrl, uint32 Flags);
extern uint32                  VARARGS68K _usbaudio_AHIsub_SetEffect(struct USBAudioIFace *, APTR Effect, struct AHIAudioCtrlDrv *AudioCtrl);
extern uint32                  VARARGS68K _usbaudio_AHIsub_LoadSound(struct USBAudioIFace *, uint16 Sound, uint32 Type, APTR Info, struct AHIAudioCtrlDrv *AudioCtrl);
extern uint32                  VARARGS68K _usbaudio_AHIsub_UnloadSound(struct USBAudioIFace *, uint16 Sound, struct AHIAudioCtrlDrv *AudioCtrl);
extern int32                   VARARGS68K _usbaudio_AHIsub_GetAttr(struct USBAudioIFace *, uint32 Attribute, int32 Argument, int32 DefValue, struct TagItem *tagList, struct AHIAudioCtrlDrv *AudioCtrl);
extern int32                   VARARGS68K _usbaudio_AHIsub_HardwareControl(struct USBAudioIFace *, uint32 Attribute, int32 Argument, struct AHIAudioCtrlDrv *AudioCtrl);


STATIC CONST APTR main_vectors[] =
{
    _usbaudio_Obtain,
    _usbaudio_Release,
    NULL,
    _usbaudio_Clone,
    _usbaudio_AHIsub_AllocAudio,
    _usbaudio_AHIsub_FreeAudio,
    _usbaudio_AHIsub_Disable,
    _usbaudio_AHIsub_Enable,
    _usbaudio_AHIsub_Start,
    _usbaudio_AHIsub_Update,
    _usbaudio_AHIsub_Stop,
    _usbaudio_AHIsub_SetVol,
    _usbaudio_AHIsub_SetFreq,
    _usbaudio_AHIsub_SetSound,
    _usbaudio_AHIsub_SetEffect,
    _usbaudio_AHIsub_LoadSound,
    _usbaudio_AHIsub_UnloadSound,
    _usbaudio_AHIsub_GetAttr,
    _usbaudio_AHIsub_HardwareControl,
    (APTR)-1
};
