#ifndef USBAUDIO_INTERFACE_DEF_H
#define USBAUDIO_INTERFACE_DEF_H

/*
 * Interface definition for usbaudio.audio AHI sub-driver.
 * Modelled after the Filesave interface generated by idltool.
 */

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif
#ifndef LIBRARIES_AHI_SUB_H
#include <libraries/ahi_sub.h>
#endif

#ifdef __cplusplus
extern "C" {
#endif

struct USBAudioIFace
{
    struct InterfaceData Data;

    uint32 APICALL (*Obtain)(struct USBAudioIFace *Self);
    uint32 APICALL (*Release)(struct USBAudioIFace *Self);
    void APICALL (*Expunge)(struct USBAudioIFace *Self);
    struct USBAudioIFace * APICALL (*Clone)(struct USBAudioIFace *Self);
    uint32 APICALL (*AHIsub_AllocAudio)(struct USBAudioIFace *Self, struct TagItem *tagList, struct AHIAudioCtrlDrv *AudioCtrl);
    void APICALL (*AHIsub_FreeAudio)(struct USBAudioIFace *Self, struct AHIAudioCtrlDrv *AudioCtrl);
    void APICALL (*AHIsub_Disable)(struct USBAudioIFace *Self, struct AHIAudioCtrlDrv *AudioCtrl);
    void APICALL (*AHIsub_Enable)(struct USBAudioIFace *Self, struct AHIAudioCtrlDrv *AudioCtrl);
    uint32 APICALL (*AHIsub_Start)(struct USBAudioIFace *Self, uint32 Flags, struct AHIAudioCtrlDrv *AudioCtrl);
    uint32 APICALL (*AHIsub_Update)(struct USBAudioIFace *Self, uint32 Flags, struct AHIAudioCtrlDrv *AudioCtrl);
    uint32 APICALL (*AHIsub_Stop)(struct USBAudioIFace *Self, uint32 Flags, struct AHIAudioCtrlDrv *AudioCtrl);
    uint32 APICALL (*AHIsub_SetVol)(struct USBAudioIFace *Self, uint16 Channel, Fixed Volume, sposition Pan, struct AHIAudioCtrlDrv *AudioCtrl, uint32 Flags);
    uint32 APICALL (*AHIsub_SetFreq)(struct USBAudioIFace *Self, uint16 Channel, uint32 Freq, struct AHIAudioCtrlDrv *AudioCtrl, uint32 Flags);
    uint32 APICALL (*AHIsub_SetSound)(struct USBAudioIFace *Self, uint16 Channel, uint16 Sound, uint32 Offset, int32 Lenght, struct AHIAudioCtrlDrv *AudioCtrl, uint32 Flags);
    uint32 APICALL (*AHIsub_SetEffect)(struct USBAudioIFace *Self, APTR Effect, struct AHIAudioCtrlDrv *AudioCtrl);
    uint32 APICALL (*AHIsub_LoadSound)(struct USBAudioIFace *Self, uint16 Sound, uint32 Type, APTR Info, struct AHIAudioCtrlDrv *AudioCtrl);
    uint32 APICALL (*AHIsub_UnloadSound)(struct USBAudioIFace *Self, uint16 Sound, struct AHIAudioCtrlDrv *AudioCtrl);
    int32 APICALL (*AHIsub_GetAttr)(struct USBAudioIFace *Self, uint32 Attribute, int32 Argument, int32 DefValue, struct TagItem *tagList, struct AHIAudioCtrlDrv *AudioCtrl);
    int32 APICALL (*AHIsub_HardwareControl)(struct USBAudioIFace *Self, uint32 Attribute, int32 Argument, struct AHIAudioCtrlDrv *AudioCtrl);
};

#ifdef __cplusplus
}
#endif

#endif /* USBAUDIO_INTERFACE_DEF_H */
